[package]
name = "slow-stac-reorg"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = { version = "1.5.6", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.51.0"
aws-smithy-types = "1.2.6"
derive_more = {version = "1.0.0", features = ["default", "from"]}
tokio = {version = "1.40.0", features = ["full"]}
